Add cassandra database support.

diff --git a/bin/run-dev-env b/bin/run-dev-env
--- a/bin/run-dev-env
+++ b/bin/run-dev-env
@@ -2,7 +2,13 @@
 
 
 # Start environment for development
-echo -e "Starting dockerized environment for development."
+if [ -z "$DB" ]
+then
+  echo -e "Missing environmental variable DB (ie: mongodb, cassandra, etc).";
+  exit 1;
+fi
+
+echo -e "Starting dockerized environment for development.";
 cd docker-compose/
-docker-compose -f network.yml -f kafka.yml -f mongodb.yml -f dev-app.yml $@
+docker-compose -f network.yml -f kafka.yml -f databases/$DB.yml -f dev-app.yml $@
 cd ../
